### ISSUE TITLE
Current binaries are not available from the downloads page

### ISSUE THREAD

**Issue by tfeb** [rowanj/gitx#130]
This is not a major issue.  I like to be able to keep tarballs (or equivalents, like dmgs) of things I install, and the last couple of GitX-dev releases have not had versions in the github downloads place.  It would be cool if they did.  Thank you!

**Comment by rowanj** [comment]
GitHub have deprecated project downloads; they don't link to it from the project page anymore or allow even project admins to upload new builds - all I can do is delete existing ones.

If you're looking for old builds, they're all accessible at URLs of the following form

`http://builds.phere.net/GitX/development/GitX-dev-[_number_].[_format_]`

Where:
- `[number]` is the last component of the version (i.e. for `GitX 0.14.61` it's _61_).  Note that only successful builds are uploaded at all; so for example there's no 58,59, or 60 because I was trying to get the deployment server operational again.  Builds before 16 didn't have automated deployment at all; and are not archived in this location.
- `[format]` is the particular file you're after; it's `zip` for most builds, `dmg` also available for 57+, or `html` for the release notes

e.g.
http://builds.phere.net/GitX/development/GitX-dev-61.dmg  --  current latest build :wink:
http://builds.phere.net/GitX/development/GitX-dev-19.zip  --  an old build
http://builds.phere.net/GitX/development/GitX-dev-37.html  --  release notes from the middle of the pack

Related: Issue #129 - Implement a substitute for GitHub downloads

**Comment by rowanj** [comment]
n.b. The last build on the downloads page is build 57; which is the immediate predecessor to 61.  There are no missing intermediates - they never made it out of the build machine.

**Comment by tfeb** [comment]
OK, well that was ... unuseful of them ....  Thanks for the links though, I will snarf a copy from there

This is resolved for me now, so I'll close it.  Thanks for your excellent work on GitX.
