### ISSUE TITLE
History view is unusable in repos with lots of commits

### ISSUE THREAD

**Issue by rgrove** [rowanj/gitx#183]
Using GitX 0.14.84.

I have a large repo with around 30,000 commits in various branches. GitX's history view tries to load every single commit on the current branch, which takes it literally hours (during which it pegs my CPU).

If I click on a commit or try to perform a search while commits are loading, the selection immediately returns to the most recent commit and the search box is cleared. If I switch to another branch, the commits start loading all over again.

This essentially makes GitX unusable for repos of any significant size. Why not have the history view load just the first few hundred commits, and only load older commits on demand?

**Comment by rowanj** [comment]
I don't think that it's just number of commits.  My commit-count test repo is the [Linux kernel](git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git), and GitX 0.14.84 fully loads the 376,583 commits of that in 65 seconds.

Scrolling through the repository and clicking commits works as expected, without re-loading anything.

Switching branch changes the working directory and the index, so I'd expect that (under the current architecture) to re-load.  That's the way GitX works, and while I'd love to not re-load the commits themselves, it's also important to actually show index changes that are made by other software.

Admittedly, not great; but not hours of CPU-pegging either.

We don't just load the first few hundred commits, because, well, that's what Tower does, and it sucks.

Troubleshooting your issue;
- what version of git are you running?
  
  pom-pom:linux rowan$ which git; git --version
  /usr/local/bin/git
  git version 1.8.2.3
- does `git gc` help?
- are you running any other software that's accessing the repository or working directory (i.e. an IDE like Xcode)
- are you running software that lives within the repo or touches files within it?
- do you have a large number of ignored files or directories?
- approximately how many branches and tags do you have? `(git branch --all; git tag) | wc -l`
- **WARNING** _destroys uncommited files:_ does `git clean -f -d -x` help?

**Comment by rgrove** [comment]
Wish I could share this repo, but it's private. :/

Could the slowness be related to the number of objects rather than the number of commits? This repo has years worth of commits for a very large codebase, with two main actively-developed branches (one of which is frequently merged into the other). At the moment it contains 442,284 total objects.

Git version: 

``` bash
$ git --version
git version 1.8.2.3
```

I don't notice any difference after running `git gc`. Only other software I'm running that's touching this directory is SublimeText 3, and I don't have any git-related extensions installed. The `.gitignore` for this repo is 9 lines long, all individual files except for one small directory.

Branches and tags:

``` bash
$ (git branch --all; git tag) | wc -l
    2558
```

...so, yeah. A lot.

`git clean -f -d -x` removed a bunch of .DS_Store files, but didn't result in any noticeable speedup in GitX.

After launching GitX a bunch of times while writing this comment, I've noticed a pattern, though: it seems to load the first 20,000 or so commits almost instantly, and then slows down significantly and begins taking 2 to 3 seconds per 100 commits. It gradually gets slower and slower as it continues.

The branch graph starts looking really wonky for those older commits (sensitive details pixelated):

![gitx](https://f.cloud.github.com/assets/1465/607097/9006a176-cd3b-11e2-96db-e8ddde8742ac.jpg)

**Comment by rowanj** [comment]
@rgrove would love if you can test this from 7a0fd3b6ccbf71ec94cfd8ef4ad6d917ec3deda5 (master) - but if it doesn't give me any trouble for the rest of the day I'll do a build this evening anyway.

**Comment by rowanj** [comment]
0.14.85 should be hitting Sparkle (in-app updates) imminently with these fixes included.

@rgrove please let me know how this performs with your repository :-)

**Comment by rgrove** [comment]
@rowanj Problem solved! My repo's history is loaded almost instantly now. Thanks so much!

**Comment by rowanj** [comment]
@rgrove glad to hear it!

**Comment by rowanj** [comment]
@rgrove I've got some substantial changes to history and commit loading coming in soon (dropping command-line Git parsing for #2), and would love if I could get your feedback on that before I push it out in an update.  My tests show it as about half the speed of 0.14.86, but still quite fast compared to before these fixes.

**Comment by rgrove** [comment]
@rowanj Sure thing. Just let me know when you're ready for me to test things.

**Comment by rowanj** [comment]
@rgrove Thanks for the offer, I'll keep you posted.

**Comment by rowanj** [comment]
@rgrove I've published a testing build with the new (non-command-line-parsing #2) history loading code; I'd love if you could give me a quick :thumbsup: or :thumbsdown:  WRT your problematic repo.

https://github.com/rowanj/gitx/releases/tag/builds/testing/1

**Comment by rgrove** [comment]
@rowanj :thumbsup: 

It's super fast! Loads history for 48,796 commits in about 3 seconds. The branch graph is also much more sane now.

**Comment by rowanj** [comment]
@rgrove Thanks!

The performance feedback I've had for this (#2) is that it's the same or faster; so I won't worry about having to revert for that.

I also much prefer the new commit sorting (it's just by date), which shows parallel branches and progress a lot more clearly, and doesn't shuffle around as much as you fetch remotes, etc.
