### ISSUE TITLE
Drag and drop branches to point to different commits

### ISSUE THREAD

**Issue by pixelcort** [rowanj/gitx#202]
The original GitX supported dragging and dropping branches to different commits.

This fork doesn't seem to have this feature anymore.

Is there a flag to turn it back on, or is it gone now?

**Comment by rowanj** [comment]
It should work fine for all local (green) branches, deliberately excluding the currently checked-out one.

**Comment by rowanj** [comment]
n.b. the current branch is excluded because:
- it introduces ambiguity into the operation ("does it affect the work dir?")
- makes it too easy to lose 'active' commits that can't be recovered without involved command-line work (see : `.git/logs/HEAD`)
- it generally promotes reset-heavy workflows;  which are unkind to teams that aren't knowledgeable about DVCS

**Comment by pixelcort** [comment]
Ah okie dokie; didn't see the non-current branch dragging still worked. Good to know the rationale. Thanks!

Closing.
