### ISSUE TITLE
Trigger "commit" by hitting Cmd+Enter from commit message box

### ISSUE THREAD

**Issue by RomainMuller** [rowanj/gitx#61]
It's a fairly small feature that I love and can barely work without - I need Cmd+Enter to issue the commit. I don't think there's any more to say about it than the title says, but I'm open to discuss as needed.

**Comment by rowanj** [comment]
Sounds good to me!

**Comment by RomainMuller** [comment]
BTW - I know that the Laullon fork has this behavior already. I decided to give your fork a try today, and that's barely the only black spot I've found so far...

**Comment by rowanj** [comment]
That's great!  Is there anything in particular that stood out?

It's been a good long while since I last merged GitX (L), and it doesn't merge anything like cleanly now.  I'm hesitant to even try for larger changes because I keep hearing rumours about poor performance on large repositories that I really don't want to introduce - my day-to-day job has a repo over 1GB in size.

There are a couple of GitX (L) things I'd like, though - like the per-branch branch indicators for relative position of the tracking branch.

**Comment by RomainMuller** [comment]
Well. You'll probably see some more issues from me in order to highlight the things I feel are missing (I've stumbled upon a few other [IMO less important, but other people may have different priorities] gaps I'd like to see fixed). I definitely think you should focus on retaining the current performance of your fork (I have the perception it's faster, despite my repos are moderate size) rather than quickly getting to feature-parity with the other forks.

Merging from @laullon's fork is probably not going to be possible anymore, since you've diverged so much (you're essentially following different philosophies, although I know @laullon intends (intended?) to stop spawning git processes in favor of libgit2 or similar (for performance). You're ahead on that front and from this perspective, his fork should merge from yours, not the other way round ;)

Last (not least), I might eventually contribute patches to help you get to parity. I had contributed a few LOCs to @laullon's fork, now I guess it's your turn ;)
