### ISSUE TITLE
Slow with large repositories

### ISSUE THREAD

**Issue by Uncommon** [rowanj/gitx#77]
My repository has gotten large recently, and now GitX beachballs a lot when it rescans.

Sample: https://gist.github.com/3539044

**Comment by rowanj** [comment]
Thanks for the sample!

I think this is largely due to the changes I made recently to reduce the bogus refreshing of the history view; it's adding most of the overhead of 'git status' to such scans, which was acceptable when I tested it (on the GitX repo itself) but is a lot worse with larger repos, yes.

I've got some changes to reduce this that will be in the next build; in the meantime I've had some luck with running `git gc` to repack the repo and the severity of the issue.

**Comment by rowanj** [comment]
This needs testing with 0.14.83+, which has fixes from #158 (#157)

**Comment by rowanj** [comment]
Assuming this is fixed.  If not, could you try https://github.com/rowanj/gitx/releases/tag/builds/testing/1 ?

**Comment by s9k** [comment]
Works much faster
